### ISSUE TITLE
Rio 2016

### ISSUE THREAD

**Issue by ariep** [wickedOne/plugin.video.nos.nl#5]
Is het ook mogelijk om de sportuitzendingen van de olympische spelen van http://nos.nl/rio2016/ te bekijken? Deze komen niet voor in de lijst met programma's, klopt dat?

**Comment by wickedOne** [comment]
dat klopt; deze plugin toont enkel wat je kan vinden op nos.nl/uitzendingen
studio rio zou er dus wél tussen moeten staan...

ik zie dat er tegenwoordig ook een [npo sport](http://nos.nl/livestream/npo-sport.html) livestream is die volgens mij precies hetzelfde uitzendt dan de link die jij vermeld.

heb destijds ook een [npo](https://github.com/wickedOne/plugin.video.npo.nl) plugin gemaakt voor de streams die momenteel hardcoded nieuws en politiek toont, maar als ik je er blij mee maak wil ik vanavond wel even kijken of ik sport kan toevoegen.

**Comment by wickedOne** [comment]
@ariep ik heb de npo plugin geupdate zodat je daar ook de sport stream op kan kijken.
zie de readme [aldaar](https://github.com/wickedOne/plugin.video.npo.nl) als je je afvraagt waarom de kwaliteit niet hoger is...

**Comment by ariep** [comment]
Dat is snel, dankjewel!
Helaas lukt het me niet om de plugin te installeren. Ik doe dit vanuit een zipfile, zoals ik je nos plugin wel succesvol heb geïnstalleerd. De foutmelding die kodi geeft bij het installeren is "dependency check failed". Dit is met kodi 15.2, misschien maakt dat nog uit. Is er een dependency die hiervoor nodig is?

**Comment by wickedOne** [comment]
ah ok, ik heb kodi hier wel op m'n laptop staan (gebruik de plugin zelf enkel onder eden).
ik ga even voor je kijken wat er allemaal nodig is...

**Comment by wickedOne** [comment]
ik heb de master branch van de npo plugin geupdate zodat die compatible is met kodi.
voor eden heb ik een speciale branch aangemaakt (zoals bij deze plugin).

bij mij lokaal installeert ie nu zonder problemen in kodi...

**Comment by ariep** [comment]
Ja, met die wijziging werkt het nu!

Je komt meteen in een specifieke stream terecht (de "actieve", met commentaar vanuit de studio), klopt dat? Het zou ideaal zijn als je zelf de sport kunt kiezen, zoals in de browser op http://nos.nl/rio2016/. Hoe dan ook, bedankt!

**Comment by wickedOne** [comment]
dat klopt inderdaad, het is de livestream van de npo die je rechtsonder ziet op nos.nl/uitzendingen onder het kopje `Live kanalen` dat was voor nu even de kortse klap.

om de keuzes te krijgen die je bij nos.nl/rio2016 ziet zou ik een aparte plugin moeten maken.
de gebruikte techniek lijkt heel veel op degene die er gebruikt wordt voor de live streams van npo.nl dus wil morgen avond wel even kijken of ik dat snel inelkaar kan hacken.

mocht het toch veel afwijken / heel veel werk zijn gaat dat helaas niet gebeuren gezien ik deze week redelijk volgeboekt ben en rio2016 een tijdelijk iets is (lees: het is geen plugin waar mensen over een maand iets aan hebben).

ik kom hier morgen even op terug en hoop dat je voor nu even geholpen bent...

w

**Comment by ariep** [comment]
OK. Ja, het heeft niet veel prioriteit natuurlijk. Mocht je makkelijk iets bij elkaar kunnen rapen, dan zou ik er wel blij mee zijn!
Met deze plugin heb ik gisteren nog mooi de beslissende set van de beachvolleybalwedstrijd kunnen kijken, dus dat was al mooi!

**Comment by wickedOne** [comment]
zie https://github.com/wickedOne/plugin.video.nos.rio2016/issues/1#issue-170282507
